### PR TITLE
fix cicd test script

### PR DESCRIPTION
**Pull request by fsx950223**
Could remove third_party?

### CODE REVIEW

**Comment by fsx950223** [comment]
> _No description provided._

Could remove third_party?

**Comment by mingxingtan** [comment]
The latest code runs well on TPU, but the keras/train.py failed on GPU with error: " TypeError: apply_gradients() got an unexpected keyword argument 'experimental_aggregate_gradients'"

Do you happen to know what's the issue?

Full log:
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)                 
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:796 step_function  **                                                                  
        outputs = model.distribute_strategy.run(run_step, args=(data,))                                                                                                            
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/one_device_strategy.py:184 run                                                      
        return super(OneDeviceStrategy, self).run(fn, args, kwargs, options)                                                                                                      
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)                
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/one_device_strategy.py:367 _call_for_each_replica
        return fn(*args, **kwargs)          
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)          
    /home/tanmingxing/git/automl/efficientdet/keras/train_lib.py:732 train_step
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer.py:378 apply_gradients
        return distribution_strategy_context.get_replica_context().merge_call(
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2715 merge_call
        return self._merge_call(merge_fn, args, kwargs)           
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2722 _merge_call
        return merge_fn(self._strategy, *args, **kwargs)          
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer.py:408 _apply_gradients_cross_replica  **
        maybe_apply_op = smart_cond.smart_cond(should_apply_grads,
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/smart_cond.py:58 smart_cond
        return control_flow_ops.cond(pred, true_fn=true_fn, false_fn=false_fn,
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)   
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:507 new_func                                                                        
        return func(*args, **kwargs)                       
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_ops.py:1180 cond
        return cond_v2.cond_v2(pred, true_fn, false_fn, name)                                                                                                     
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/cond_v2.py:79 cond_v2                                                      
        true_graph = func_graph_module.func_graph_from_py_func(                                                                                                      
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py:986 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer.py:394 apply_fn
        return distribution.extended.call_for_each_replica(
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/one_device_strategy.py:367 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/tanmingxing/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer.py:418 _apply_gradients
        return self._optimizer.apply_gradients(

    TypeError: apply_gradients() got an unexpected keyword argument 'experimental_aggregate_gradients'

**Comment by fsx950223** [comment]
> experimental_aggregate_gradients

The bug has been fixed in [tfa-nightly](https://github.com/tensorflow/addons/pull/2137)

**Review by mingxingtan — APPROVED** [review]

**Comment by mingxingtan** [comment]
Maybe

> > experimental_aggregate_gradients
> 
> The bug has been fixed in [tfa-nightly](https://github.com/tensorflow/addons/pull/2137)

Maybe we can update the requirements to include the tfa-nightly?

**Comment by fsx950223** [comment]
> Maybe
> 
> > > experimental_aggregate_gradients
> > 
> > 
> > The bug has been fixed in [tfa-nightly](https://github.com/tensorflow/addons/pull/2137)
> 
> Maybe we can update the requirements to include the tfa-nightly?

Both are fine to me. I guess tensorflow-addons will release 0.12 in few days.

**Pull request merged**
