### PR TITLE
fix channels bug

### PR DESCRIPTION
**Pull request by fsx950223**
I forget to add transpose when I submit pull request.
@mingxingtan

### CODE REVIEW

**Comment by mingxingtan** [comment]
Thanks @fsx950223 Does it work with saved_model_infer now?

**Comment by fsx950223** [comment]
> Thanks @fsx950223 Does it work with saved_model_infer now?

I just test infer. I believe they have the same behavior and you need to export new saved model.

**Comment by mingxingtan** [comment]
Just tested, seems still not working on my side. Do you just change the data_format to 'channel_first' in hparams_config.py?

**Comment by fsx950223** [comment]
> Just tested, seems still not working on my side. Do you just change the data_format to 'channel_first' in hparams_config.py?

yes

**Comment by fsx950223** [comment]
Screenshot from 2020-04-20 16-36-24

**Pull request merged**
