### PR TITLE
In infer mode for the parameter of num_classes is invalid, So loading the model causes errors, if my num_classes=2

### PR DESCRIPTION
**Pull request by HK017**
hello, @mingxingtan, my custom dataset have 2 classes, i convert the dataset to coco format; The training process is normal, but predict some images, I looked at the picture results, to my surprise, only one category can be predicted，another category of object is missing in predicting images. I also asked my questions #81 .Later, it was found that there was a problem in the conversion of the script I wrote. The category should start from 1, but I started from 0, which led to this problem, finally, I solved the problem. Today, I tested my training model and used your tutorial, but found that the modification of num classes is invalid, and an error will be reported when loading the model. I debugged your code and found that the num classes parameter of the command line did not modify the num classes in config, so I proposed my request.

### CODE REVIEW

**Comment by mingxingtan** [comment]
Hi @HK017, Thanks for the PR. The changes look good to me. Could you sign the CLA, so I can merge your PR?

**Comment by HK017** [comment]
@mingxingtan  yes，i can't visit https://cla.developers.google.com/  to sign CLA, SO you can merge

**Comment by HK017** [comment]
> Hi @HK017, Thanks for the PR. The changes look good to me. Could you sign the CLA, so I can merge your PR?

@mingxingtan yes，i can't visit https://cla.developers.google.com/ to sign CLA, So you can merge.

**Comment by HK017** [comment]
> @googlebot

@googlebot  I signed it!

**Comment by HK017** [comment]
> @googlebot I fixed it.

@googlebot I fixed it.

**Comment by HK017** [comment]
@googlebot I fixed it.

**Comment by HK017** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and then comment `@googlebot I fixed it.`. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fautoml%2Fpull%2F101) for more info**.

**Comment by HK017** [comment]
@googlebot I fixed it.

**Comment by HK017** [comment]
@googlebot I signed it!

**Comment by HK017** [comment]
@googlebot I fixed it.

**Comment by HK017** [comment]
> Hi @HK017, Thanks for the PR. The changes look good to me. Could you sign the CLA, so I can merge your PR?

Sorry, there's something wrong with my CLA, I hope you can modify the code to benefit more users, if you can see. Ha-ha, my English is very poor and hope you will not mind it!

**Comment by HK017** [comment]
> > Hi @HK017, Thanks for the PR. The changes look good to me. Could you sign the CLA, so I can merge your PR?
> 
> @mingxingtan yes，i can't visit https://cla.developers.google.com/ to sign CLA, So you can merge.

@mingxingtan  Sorry, there's something wrong with my CLA, I hope you can modify the code to benefit more users, if you can see. Ha-ha, my English is very poor and hope you will not mind it!

**Comment by mingxingtan** [comment]
I manually added in https://github.com/google/automl/commit/ec266c0bc846e99ebd4fa915df2efaf549d3084e.

Thanks for pointing this out!

**Pull request closed without merging**
