### PR TITLE
:zap: Added visualization script

### PR DESCRIPTION
**Pull request by kartik4949**
Solves #838 
I think this will be helpful for early signs of bad dataset, it can save unnecessary issues and debugging time which could have been a silly data format or labelling issue.
I can add this script to visualize folder too.
@mingxingtan @fsx950223 thoughts?

p.s: @fsx950223 suggested to use tfrecords viewer but I think this solves third party tool usages and will be very handy.

### CODE REVIEW

**Comment by kartik4949** [comment]
@mingxingtan if it is a go from you, i can proceed with this pr and complete it. i.e configurable, adding label, readme update.

**Comment by mingxingtan** [comment]
Hi @kartik4949  Thanks for adding this. Please don't modify TF1 version of main.py as we are moving to TF2.
Looks like this PR is only about dataset, maybe you can add a standalone tool in dataset (such as dataset/inspect_tfrecord.py)?

**Comment by kartik4949** [comment]
@mingxingtan alrite, makes sense
Let me add this in dataset
Thanks!

**Comment by kartik4949** [comment]
@mingxingtan  done, can you suggest tests?

**Comment by kartik4949** [comment]
@mingxingtan 
so this script saves  images, bboxes formed by input dataloader with given flag '-train', configuration passed in config.yaml /hparams.

Visualize train tfrecord with augmentation.
``` 
python dataset/inspect_tfrecords.py --file_pattern dataset/sample.record --model_name "efficientdet-d0" --save_samples_dir visualize_dataset/  -train -hparams="label_map={1:'type1'}, autoaugment_policy=v3"

# above command builds dataloader equivalent with config.yaml/hparams.
# visualizes images and bboxes with given label_map.
# train = True
```

**Review by mingxingtan — APPROVED** [review]
LGTM. Thanks for adding this tool

**Comment by ngaloppo** [comment]
@kartik4949 What's the difference between train & eval mode for the visualization tool? Why do you need both?

**Comment by kartik4949** [comment]
@ngaloppo eval mode wont have any augmentations 
Train will have it

**Comment by kartik4949** [comment]
a

**Pull request merged**
