### PR TITLE
Benchmark

### PR DESCRIPTION
**Pull request by fsx950223**
Add benchmark test and refact saved model inference

### CODE REVIEW

**Comment by fsx950223** [comment]
cc @mingxingtan

**Comment by mingxingtan** [comment]
@fsx950223 Thank you! Yes, this is super useful!  Do you happen to have any benchmark results on GPU?

I will let this CL in, but we may need to change the default score_threshhold=0.5 and max_box_to_draw to make the benchmark latency comparable to others (if postprocessing is sensitive to score_threshhold)

**Comment by fsx950223** [comment]
> @fsx950223 Thank you! Yes, this is super useful! Do you happen to have any benchmark results on GPU?
> 
> I will let this CL in, but we may need to change the default score_threshhold=0.5 and max_box_to_draw to make the benchmark latency comparable to others (if postprocessing is sensitive to score_threshhold)

My GPU is busy now and I will test benchmark later.

**Comment by fsx950223** [comment]
> @fsx950223 Thank you! Yes, this is super useful! Do you happen to have any benchmark results on GPU?
> 
> I will let this CL in, but we may need to change the default score_threshhold=0.5 and max_box_to_draw to make the benchmark latency comparable to others (if postprocessing is sensitive to score_threshhold)

I got about 10FPS on GTX1080TI, 0.093s per image.
I found top_kv2 is the main reason for low latency and I don't know why there are a lot of unknown ops.
Here is chrome trace.
Screenshot from 2020-04-15 15-33-32

**Comment by mingxingtan** [comment]
Hmm, these unknown ops maybe just waiting for GPU executing?  Could you help upload your trace file?

**Comment by fsx950223** [comment]
> Hmm, these unknown ops maybe just waiting for GPU executing? Could you help upload your trace file?

[Here](https://drive.google.com/open?id=1iNP-SVJODY_QIyk3aosk4ToZ25JytYLa)

**Comment by fsx950223** [comment]
Change to one-shot detector could speed up latency but may lose some mAP.

**Comment by HongweiChe** [comment]
and i have the same issue. I got about 15.7FPS on GTX2080TI, 0.063s per image.

**Comment by fsx950223** [comment]
> and i have the same issue. I got about 15.7FPS on GTX2080TI, 0.063s per image.

It's 65fps on 2080ti now.

**Pull request merged**
