### PR TITLE
fix dependencies

### LINKED ISSUE #135: AA could not be used , NameError: name 'contrib_image' is not defined
/home/kenny70037/automl/efficientdet/aug/autoaugment.py:1370 <lambda>
        image, bboxes, pixels, replace, shift_horizontal=True),
    /home/kenny70037/automl/efficientdet/aug/autoaugment.py:947 translate_bbox
        image = translate_x(image, pixels, replace)
    /home/kenny70037/automl/efficientdet/aug/autoaugment.py:877 translate_x
        image = contrib_image.translate(wrap(image), [-pixels, 0])

    NameError: name 'contrib_image' is not defined

I have successed in pretrain model in TPU, and when I'm trying  to use AA , facing this problem.

### PR DESCRIPTION
**Pull request by fsx950223**
Fix #135

### CODE REVIEW

**Comment by b03505036** [comment]
Could it work? I fixed in the same way, but still facing some problem. 
After my TPU training, I will try again and take a screenshot for you.
Thanks for your fix !

**Comment by b03505036** [comment]
File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3082, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.NotFoundError: in converted code:

    /home/kenny70037/automl/efficientdet/dataloader.py:303 _dataset_parser
        image, boxes, params['autoaugment_policy'])
    /home/kenny70037/.local/lib/python3.7/site-packages/tensorflow_addons/image/translate_ops.py:101 translate  *
        return transform(
    /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/eager/def_function.py:568 __call__
        result = self._call(*args, **kwds)
    /home/kenny70037/.local/lib/python3.7/site-packages/tensorflow_addons/image/transform_ops.py:110 transform  *
        output = _image_so.ops.addons_image_projective_transform_v2(
    /home/kenny70037/.local/lib/python3.7/site-packages/tensorflow_addons/utils/resource_loader.py:49 ops
        self._ops = tf.load_op_library(get_path_to_datafile(self.relative_path))
    /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/load_library.py:57 load_op_library
        lib_handle = py_tf.TF_LoadLibrary(library_filename)

    NotFoundError: /home/kenny70037/.local/lib/python3.7/site-packages/tensorflow_addons/custom_ops/image/_image_ops.so: undefined symbol: __cudaPushCallConfiguration

**Comment by b03505036** [comment]
By the way, Im using TPU. 
Did it mean I cannot use AA on TPU, because it needs "cuda" ?

**Comment by fsx950223** [comment]
> By the way, Im using TPU. 
> Did it mean I cannot use AA on TPU, because it needs "cuda" ?

Please install tensorflow instead of tensorflow-cpu

**Comment by b03505036** [comment]
@fsx950223 I did install tensorflow and tensorflow-cpu both.
Should I remove the cpu one?

**Comment by fsx950223** [comment]
yes

**Comment by b03505036** [comment]
After I removed tensorflow-cpu, it could not work.

Traceback (most recent call last):
  File "main.py", line 27, in <module>
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow'

which device do you do the test on TPU or GPU?

**Comment by fsx950223** [comment]
> After I removed tensorflow-cpu, it could not work.
> 
> Traceback (most recent call last):
> File "main.py", line 27, in
> import tensorflow.compat.v1 as tf
> ModuleNotFoundError: No module named 'tensorflow'
> 
> which device do you do the test on TPU or GPU?

Could you reinstall tensorflow?

**Comment by b03505036** [comment]
I reinstall it, run it again and got 
W0402 10:53:04.235654 140544863176512 deprecation.py:323] From /usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py:751: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Variable.assign which has equivalent behavior in 2.X.
INFO:tensorflow:training_loop marked as finished
I0402 10:53:08.172337 140544863176512 error_handling.py:108] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0402 10:53:08.172548 140544863176512 error_handling.py:142] Reraising captured error
Traceback (most recent call last):
  File "/home/kenny70038/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/home/kenny70038/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/home/kenny70038/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: From /job:worker/replica:0/task:0:
Op type not registered 'Addons>ImageProjectiveTransformV2' in binary running on n-046092ea-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
         [[{{node input_pipeline_task0/OptimizeDataset}}]]

**Comment by b03505036** [comment]
And thank you for reply.

**Comment by fsx950223** [comment]
You specific autoaugument runs on cpu

**Comment by b03505036** [comment]
Could you talk it more in detail? 
thank you.

Do you mean that I'm not using tensorflow but using tensorflow-cpu?

**Comment by fsx950223** [comment]
As Tensorflow addons don't support TPU, could you specific autoaugment runs on CPU? @mingxingtan

**Comment by fsx950223** [comment]
> Could you talk it more in detail?
> thank you.
> 
> Do you mean that I'm not using tensorflow but using tensorflow-cpu?

I'm afraid that you have to use tf1.x for AA with tpu.

**Comment by b03505036** [comment]
@fsx950223 thank you very much!

**Pull request merged**
