### PR TITLE
p.add_(torch.sign(update), alpha=-group['lr']) has been made more eff…

### PR DESCRIPTION
**Pull request by sachinspanicker**
…icient by using the torch.sign function's inplace mode. This will prevent the need to create a new tensor for the updated parameter, which can save a significant amount of time for large models.

### CODE REVIEW

**Comment by crazydonkey200** [comment]
Sorry that I have missed this pull request earlier. Thanks for the contribution!

**Comment by liuslnlp** [comment]
Error
```
add_() received an invalid combination of arguments - got unrecognized keyword arguments: inplace
```

My torch version
```
>>> import torch
>>> torch.__version__
'2.1.0.dev20230829+cu121'
```

**Comment by fbotp** [comment]
@liuslnlp  `add_` is already an **inplace** method, so I remove this parameter in method, and it works, you can have a try

**Comment by yongchanghao** [comment]
@crazydonkey200  As the comments above suggested, there isn't such an argument as `inplace=True` in `torch.Tensor.add_`. for both torch versions above or under 2.0. I believe this code hasn't been tested.

**Pull request merged**
