### PR TITLE
keras refact

### PR DESCRIPTION
**Pull request by fsx950223**
Refact with keras and get same output with tf1.x.

### CODE REVIEW

**Comment by fsx950223** [comment]
I wonder why not use ```Conv2DTranspose``` for upsample? @mingxingtan

**Comment by Ely-S** [comment]
@fsx950223 I love this! Refactoring to keras seems big. Is there any place I can help? Maybe we can divide and conquer.

**Comment by fsx950223** [comment]
> @fsx950223 I love this! Refactoring to keras seems big. Is there any place I can help? Maybe we can divide and conquer.

Transfer tf1.x API to keras API

**Comment by Ely-S** [comment]
I'm starting to implement `build_bifpn_layer` as keras layer.

**Comment by VicariNishimura** [comment]
You want to change layers to tf.keras or you aim to refactor the code into keras model ? Because the use of TPUEstimator is maybe a problem.

**Comment by Ely-S** [comment]
@VicariNishimura my goal is to turn `def build_bifpn_layer(...)` into class `BiFPNLater(tf.keras.layers.Layer)`. It's challenging because build_bifpn_layer doesn't seem deterministic. 

Keras layers can be used anywhere graph operations are possible.

**Comment by VicariNishimura** [comment]
So, Backbone is already a tf.keras.Model, BoxNet/ClassNet are easy to convert to tf.keras.Model, and if you succeed to convert FPN to tf.keras.model this mean that we can use tf.keras for efficientdet and all (awesome) tools that come with it (mot, distibution, ...) ?

**Comment by Ely-S** [comment]
@VicariNishimura That's the goal

**Comment by LucasSloan** [comment]
Is there anything I can do to help?

**Comment by mingxingtan** [comment]
Hi @fsx950223, I forgot to mention in this PR yesterday. Could you help move them to efficientdet/keras folder?   (rename the keras_impl to keras) Thanks!

**Comment by mingxingtan** [comment]
@fsx950223 looks like there are some conflicts. Could you help resolve these conflicts? Thanks.

Also, some lines seem to be too long (Google has a restriction of each line has up to 80 character). Would be great if you can help run:

pylint --rcfile=../.pylint.rc  xx.py

Thank you!

**Comment by mingxingtan** [comment]
Looks much better, thank you @fsx950223 !

**Pull request merged**
