### PR TITLE
fix nms

### PR DESCRIPTION
**Pull request by fsx950223**
Inference time:  0.03094419360975735
FPS: 32.31624041043613
GTX1080TI, NCHW, batch_size=1, XLA
@mingxingtan 

Class-specific filter NMS is useless. Change to global NMS gets a huge performance improvement and the same accuracy. The related work has been done by top_k.

### CODE REVIEW

**Comment by fsx950223** [comment]
I believe the model is much faster than other repos now.

**Comment by mingxingtan** [comment]
Wow, this is amazing!  Thank you so much. @fsx950223 

I merged the previous data_format PR, after that, this PR has some conflicts. Could you do a sync to resolve the conflicts?

**Comment by fsx950223** [comment]
Done

**Comment by mingxingtan** [comment]
Again, thank you so much, @fsx950223.
I would like to add a new update in the README page to high this speedup. Do you mind if I add your github name (or other name that you prefer) to highlight your contribution to this incredible speedup?

**Comment by fsx950223** [comment]
> Again, thank you so much, @fsx950223.
> I would like to add a new update in the README page to high this speedup. Do you mind if I add your github name (or other name that you prefer) to highlight your contribution to this incredible speedup?

I'm willing to be highlighted.

**Comment by mingxingtan** [comment]
I just profiled the runtime and it seems there are still a lot of TopKV2 ops (but those extra overhead after TopK are gone thanks to this PR):

image

I would like to further look into the issue to see whether we can reduce this overhead. Let me know if you happen to see some helpful information.

**Comment by fsx950223** [comment]
> I just profiled the runtime and it seems there are still a lot of TopKV2 ops (but those extra overhead after TopK are gone thanks to this PR):
> 
> image
> 
> I would like to further look into the issue to see whether we can reduce this overhead. Let me know if you happen to see some helpful information.

I believe they are the same op but record several times.

**Comment by fsx950223** [comment]
> I just profiled the runtime and it seems there are still a lot of TopKV2 ops (but those extra overhead after TopK are gone thanks to this PR):
> 
> image
> 
> I would like to further look into the issue to see whether we can reduce this overhead. Let me know if you happen to see some helpful information.

I found another problem, the performance will slow down a lot when I use a bigger network or a bigger num_classes. It will cost a lot of time to build heap.
Is it reasonable to use top_k?

**Comment by mingxingtan** [comment]
Yeah, top_k is a big problem. I realized that tf.image.combined_non_max_suppression might help get rid of top_k. I am trying a implementation now.

**Comment by fsx950223** [comment]
> Yeah, top_k is a big problem. I realized that tf.image.combined_non_max_suppression might help get rid of top_k. I am trying a implementation now.

I found that I could use ```tf.where``` filter cls_outputs by sigmoid scores, it may faster than top_k. I try it later.

**Pull request merged**
